In [1]:
print('hello')

hello


In [2]:
# pip install --upgrade pip

In [3]:
# pip install auto-sklearn

In [4]:
# pip install auto-sklearn

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so
import missingno as msno 
import os
from fancyimpute import IterativeImputer# Window의 한글 폰트 설정
plt.rc('font', family='Malgun Gothic')
plt.rc('axes', unicode_minus=False)
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import RobustScaler
# import autosklearn.classification
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

%config InlineBackend.figure_format = 'retina'

In [6]:
os.getcwd()

'c:\\Users\\정호원\\OneDrive\\바탕 화면\\baf\\치매 프로젝트\\0428 모델링'

In [7]:
df = pd.read_csv('final_modeling_data.csv',encoding='cp949')
df_val = pd.read_csv('final_modeling_val_data.csv',encoding='cp949')

In [8]:
df.head()

Unnamed: 0             EMAIL  activity_average_met  activity_cal_active  \
0           0  nia+279@rowan.kr               1.28125                  196   
1           1  nia+279@rowan.kr               1.25000                  145   
2           2  nia+279@rowan.kr               1.21875                  118   
3           3  nia+279@rowan.kr               1.28125                  180   
4           4  nia+279@rowan.kr               1.46875                  374   

   activity_cal_total  activity_daily_movement  activity_high  \
0                2251                     3353              0   
1                2159                     2516              0   
2                2140                     1716              0   
3                2240                     2791              0   
4                2559                     5393              0   

   activity_inactive  activity_inactivity_alerts  activity_low  ...  \
0                714                           0           201  ...   
1                719                           0           131  ...   
2                708                           1           125  ...   
3                705                           0           203  ...   
4                437                           0           511  ...   

   sleep_onset_latency  sleep_period_id  sleep_rem  sleep_restless  \
0                  630                0       3780              24   
1                  930                1       2850              25   
2                  330                0       4530              35   
3                  510                3       4860              21   
4                  420                0       1740              29   

   sleep_rmssd  sleep_temperature_delta  sleep_total  DIAG_NM    Rating  TOTAL  
0           39                     0.00        29220      MCI  0.014538     72  
1           38                     0.34        22110      MCI  0.014538     72  
2           47                    -0.07        21510      MCI  0.014538     72  
3           44                    -0.14        21360      MCI  0.014538     72  
4           56                    -0.50        13530      MCI  0.014538     72  

[5 rows x 40 columns]

In [9]:
df

Unnamed: 0             EMAIL  activity_average_met  activity_cal_active  \
0              0  nia+279@rowan.kr               1.28125                  196   
1              1  nia+279@rowan.kr               1.25000                  145   
2              2  nia+279@rowan.kr               1.21875                  118   
3              3  nia+279@rowan.kr               1.28125                  180   
4              4  nia+279@rowan.kr               1.46875                  374   
...          ...               ...                   ...                  ...   
9700        9700  nia+206@rowan.kr               1.34375                  249   
9701        9701  nia+206@rowan.kr               1.53125                  570   
9702        9702  nia+206@rowan.kr               1.34375                  295   
9703        9703  nia+206@rowan.kr               1.31250                  186   
9704        9704  nia+206@rowan.kr               1.37500                   83   

      activity_cal_total  activity_daily_movement  activity_high  \
0                   2251                     3353              0   
1                   2159                     2516              0   
2                   2140                     1716              0   
3                   2240                     2791              0   
4                   2559                     5393              0   
...                  ...                      ...            ...   
9700                2351                     4411              1   
9701                2682                    11057              1   
9702                2331                     5135              4   
9703                2280                     3178              0   
9704                1891                     1554              0   

      activity_inactive  activity_inactivity_alerts  activity_low  ...  \
0                   714                           0           201  ...   
1                   719                           0           131  ...   
2                   708                           1           125  ...   
3                   705                           0           203  ...   
4                   437                           0           511  ...   
...                 ...                         ...           ...  ...   
9700                780                           4           167  ...   
9701                518                           1           332  ...   
9702                578                           0           173  ...   
9703                778                           1           138  ...   
9704                 69                           0            61  ...   

      sleep_onset_latency  sleep_period_id  sleep_rem  sleep_restless  \
0                     630                0       3780              24   
1                     930                1       2850              25   
2                     330                0       4530              35   
3                     510                3       4860              21   
4                     420                0       1740              29   
...                   ...              ...        ...             ...   
9700                  450                0       6330              52   
9701                  600                0       5880              57   
9702                 1140                1       7740              52   
9703                  630                0       5700              48   
9704                  870                0       5010              55   

      sleep_rmssd  sleep_temperature_delta  sleep_total  DIAG_NM    Rating  \
0              39                     0.00        29220      MCI  0.014538   
1              38                     0.34        22110      MCI  0.014538   
2              47                    -0.07        21510      MCI  0.014538   
3              44                    -0.14        21360      MCI  0.014538   
4              56                    -0.50        13530     

In [10]:
df_val.head()

Unnamed: 0             EMAIL  activity_average_met  activity_cal_active  \
0           0  nia+404@rowan.kr               1.71875                  730   
1           1  nia+404@rowan.kr               1.40625                  342   
2           2  nia+404@rowan.kr               1.46875                  401   
3           3  nia+404@rowan.kr               0.34375                   27   
4           4  nia+404@rowan.kr               1.46875                  333   

   activity_cal_total  activity_daily_movement  activity_high  \
0                2944                    14346              0   
1                2449                     6352              0   
2                2544                     7297              0   
3                1850                      491              0   
4                2518                     5861              0   

   activity_inactive  activity_inactivity_alerts  activity_low  ...  \
0                417                           0           545  ...   
1                473                           0           392  ...   
2                586                           0           362  ...   
3                176                           0            34  ...   
4                646                           0           377  ...   

   sleep_onset_latency  sleep_period_id  sleep_rem  sleep_restless  \
0                  960                0       4380              47   
1                  690                0       2400              56   
2                 1140                0       2760              48   
3                 1170                0       1980              59   
4                 3360                0       3570              42   

   sleep_rmssd  sleep_temperature_delta  sleep_total  DIAG_NM    Rating  TOTAL  
0           20                    -0.12        21510       CN  0.013152     88  
1           19                    -0.32        17040       CN  0.013152     88  
2           26                     0.07        21360       CN  0.013152     88  
3           30                    -0.41        20100       CN  0.013152     88  
4           23                    -0.27        20730       CN  0.013152     88  

[5 rows x 40 columns]

In [11]:
df_val

Unnamed: 0             EMAIL  activity_average_met  activity_cal_active  \
0              0  nia+404@rowan.kr               1.71875                  730   
1              1  nia+404@rowan.kr               1.40625                  342   
2              2  nia+404@rowan.kr               1.46875                  401   
3              3  nia+404@rowan.kr               0.34375                   27   
4              4  nia+404@rowan.kr               1.46875                  333   
...          ...               ...                   ...                  ...   
2473        2473  nia+280@rowan.kr               1.59375                  648   
2474        2474  nia+280@rowan.kr               1.43750                  379   
2475        2475  nia+280@rowan.kr               1.56250                  670   
2476        2476  nia+280@rowan.kr               1.46875                  556   
2477        2477  nia+280@rowan.kr               1.34375                  311   

      activity_cal_total  activity_daily_movement  activity_high  \
0                   2944                    14346              0   
1                   2449                     6352              0   
2                   2544                     7297              0   
3                   1850                      491              0   
4                   2518                     5861              0   
...                  ...                      ...            ...   
2473                2760                    12256              0   
2474                2507                     6973              0   
2475                2747                    13008              0   
2476                2570                    11043              0   
2477                2341                     5943              0   

      activity_inactive  activity_inactivity_alerts  activity_low  ...  \
0                   417                           0           545  ...   
1                   473                           0           392  ...   
2                   586                           0           362  ...   
3                   176                           0            34  ...   
4                   646                           0           377  ...   
...                 ...                         ...           ...  ...   
2473                444                           0           381  ...   
2474                623                           0           361  ...   
2475                422                           0           366  ...   
2476                452                           2           244  ...   
2477                595                           0           277  ...   

      sleep_onset_latency  sleep_period_id  sleep_rem  sleep_restless  \
0                     960                0       4380              47   
1                     690                0       2400              56   
2                    1140                0       2760              48   
3                    1170                0       1980              59   
4                    3360                0       3570              42   
...                   ...              ...        ...             ...   
2473                 1140                0       1470              30   
2474                  930                0       6510              33   
2475                  450                0       4140              42   
2476                  360                0       7650              27   
2477                 1200                0       1590              53   

      sleep_rmssd  sleep_temperature_delta  sleep_total  DIAG_NM    Rating  \
0              20                    -0.12        21510       CN  0.013152   
1              19                    -0.32        17040       CN  0.013152   
2              26                     0.07        21360       CN  0.013152   
3              30                    -0.41        20100       CN  0.013152   
4              23                    -0.27        20730     

In [12]:
df.columns

Index(['Unnamed: 0', 'EMAIL', 'activity_average_met', 'activity_cal_active',
       'activity_cal_total', 'activity_daily_movement', 'activity_high',
       'activity_inactive', 'activity_inactivity_alerts', 'activity_low',
       'activity_medium', 'activity_met_min_high', 'activity_met_min_inactive',
       'activity_met_min_low', 'activity_met_min_medium', 'activity_non_wear',
       'activity_rest', 'activity_steps', 'activity_total', 'sleep_awake',
       'sleep_breath_average', 'sleep_deep', 'sleep_duration',
       'sleep_efficiency', 'sleep_hr_average', 'sleep_hr_lowest',
       'sleep_is_longest', 'sleep_light', 'sleep_midpoint_at_delta',
       'sleep_midpoint_time', 'sleep_onset_latency', 'sleep_period_id',
       'sleep_rem', 'sleep_restless', 'sleep_rmssd', 'sleep_temperature_delta',
       'sleep_total', 'DIAG_NM', 'Rating', 'TOTAL'],
      dtype='object')

In [13]:
# ***** 한 번만 하고 말아야됨 *****
df = df.drop(df.columns[[0, 1]], axis=1)

In [14]:
# ***** 한 번만 하고 말아야됨 *****
df_val = df_val.drop(df_val.columns[[0, 1]], axis=1)

In [15]:
df.head()

activity_average_met  activity_cal_active  activity_cal_total  \
0               1.28125                  196                2251   
1               1.25000                  145                2159   
2               1.21875                  118                2140   
3               1.28125                  180                2240   
4               1.46875                  374                2559   

   activity_daily_movement  activity_high  activity_inactive  \
0                     3353              0                714   
1                     2516              0                719   
2                     1716              0                708   
3                     2791              0                705   
4                     5393              0                437   

   activity_inactivity_alerts  activity_low  activity_medium  \
0                           0           201                6   
1                           0           131                9   
2                           1           125                6   
3                           0           203                5   
4                           0           511                6   

   activity_met_min_high  ...  sleep_onset_latency  sleep_period_id  \
0                      0  ...                  630                0   
1                      0  ...                  930                1   
2                      0  ...                  330                0   
3                      0  ...                  510                3   
4                      0  ...                  420                0   

   sleep_rem  sleep_restless  sleep_rmssd  sleep_temperature_delta  \
0       3780              24           39                     0.00   
1       2850              25           38                     0.34   
2       4530              35           47                    -0.07   
3       4860              21           44                    -0.14   
4       1740              29           56                    -0.50   

   sleep_total  DIAG_NM    Rating  TOTAL  
0        29220      MCI  0.014538     72  
1        22110      MCI  0.014538     72  
2        21510      MCI  0.014538     72  
3        21360      MCI  0.014538     72  
4        13530      MCI  0.014538     72  

[5 rows x 38 columns]

In [16]:
df_val.head()

activity_average_met  activity_cal_active  activity_cal_total  \
0               1.71875                  730                2944   
1               1.40625                  342                2449   
2               1.46875                  401                2544   
3               0.34375                   27                1850   
4               1.46875                  333                2518   

   activity_daily_movement  activity_high  activity_inactive  \
0                    14346              0                417   
1                     6352              0                473   
2                     7297              0                586   
3                      491              0                176   
4                     5861              0                646   

   activity_inactivity_alerts  activity_low  activity_medium  \
0                           0           545               47   
1                           0           392                8   
2                           0           362               24   
3                           0            34                1   
4                           0           377                6   

   activity_met_min_high  ...  sleep_onset_latency  sleep_period_id  \
0                      0  ...                  960                0   
1                      0  ...                  690                0   
2                      0  ...                 1140                0   
3                      0  ...                 1170                0   
4                      0  ...                 3360                0   

   sleep_rem  sleep_restless  sleep_rmssd  sleep_temperature_delta  \
0       4380              47           20                    -0.12   
1       2400              56           19                    -0.32   
2       2760              48           26                     0.07   
3       1980              59           30                    -0.41   
4       3570              42           23                    -0.27   

   sleep_total  DIAG_NM    Rating  TOTAL  
0        21510       CN  0.013152     88  
1        17040       CN  0.013152     88  
2        21360       CN  0.013152     88  
3        20100       CN  0.013152     88  
4        20730       CN  0.013152     88  

[5 rows x 38 columns]

In [17]:
df.columns

Index(['activity_average_met', 'activity_cal_active', 'activity_cal_total',
       'activity_daily_movement', 'activity_high', 'activity_inactive',
       'activity_inactivity_alerts', 'activity_low', 'activity_medium',
       'activity_met_min_high', 'activity_met_min_inactive',
       'activity_met_min_low', 'activity_met_min_medium', 'activity_non_wear',
       'activity_rest', 'activity_steps', 'activity_total', 'sleep_awake',
       'sleep_breath_average', 'sleep_deep', 'sleep_duration',
       'sleep_efficiency', 'sleep_hr_average', 'sleep_hr_lowest',
       'sleep_is_longest', 'sleep_light', 'sleep_midpoint_at_delta',
       'sleep_midpoint_time', 'sleep_onset_latency', 'sleep_period_id',
       'sleep_rem', 'sleep_restless', 'sleep_rmssd', 'sleep_temperature_delta',
       'sleep_total', 'DIAG_NM', 'Rating', 'TOTAL'],
      dtype='object')

In [18]:
df_val.columns

Index(['activity_average_met', 'activity_cal_active', 'activity_cal_total',
       'activity_daily_movement', 'activity_high', 'activity_inactive',
       'activity_inactivity_alerts', 'activity_low', 'activity_medium',
       'activity_met_min_high', 'activity_met_min_inactive',
       'activity_met_min_low', 'activity_met_min_medium', 'activity_non_wear',
       'activity_rest', 'activity_steps', 'activity_total', 'sleep_awake',
       'sleep_breath_average', 'sleep_deep', 'sleep_duration',
       'sleep_efficiency', 'sleep_hr_average', 'sleep_hr_lowest',
       'sleep_is_longest', 'sleep_light', 'sleep_midpoint_at_delta',
       'sleep_midpoint_time', 'sleep_onset_latency', 'sleep_period_id',
       'sleep_rem', 'sleep_restless', 'sleep_rmssd', 'sleep_temperature_delta',
       'sleep_total', 'DIAG_NM', 'Rating', 'TOTAL'],
      dtype='object')

In [19]:
X_train = df.drop('DIAG_NM', axis=1)  # 타겟 변수를 제외한 모든 열을 특성으로 선택
y_train = df['DIAG_NM']  # 타겟 변수로 'DIAG_NM'을 선택

X_val = df_val.drop('DIAG_NM', axis=1)
y_val = df_val['DIAG_NM']

# 의사 결정 트리 모델 생성
model = DecisionTreeClassifier()

# 모델 훈련
model.fit(X_train, y_train)

# 검증 데이터로 예측
y_pred = model.predict(X_val)

# 정확도 계산
accuracy = accuracy_score(y_val, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.29539951573849876


In [20]:
from sklearn.ensemble import RandomForestClassifier

# 랜덤 포레스트 모델 생성
rf_model = RandomForestClassifier()

# 모델 훈련
rf_model.fit(X_train, y_train)

# 검증 데이터로 예측
y_pred_rf = rf_model.predict(X_val)

# 정확도 계산
accuracy_rf = accuracy_score(y_val, y_pred_rf)
print("Random Forest Accuracy:", accuracy_rf)

Random Forest Accuracy: 0.2784503631961259


In [21]:
from sklearn.linear_model import LogisticRegression

# 로지스틱 회귀 모델 생성
logistic_model = LogisticRegression()

# 모델 훈련
logistic_model.fit(X_train, y_train)

# 검증 데이터로 예측
y_pred_logistic = logistic_model.predict(X_val)

# 정확도 계산
accuracy_logistic = accuracy_score(y_val, y_pred_logistic)
print("Logistic Regression Accuracy:", accuracy_logistic)

Logistic Regression Accuracy: 0.744955609362389


In [25]:
from sklearn.svm import SVC

# SVM 모델 생성
svm_model = SVC()

# 모델 훈련
svm_model.fit(X_train, y_train)

# 검증 데이터로 예측
y_pred_svm = svm_model.predict(X_val)

# 정확도 계산
accuracy_svm = accuracy_score(y_val, y_pred_svm)
print("SVM Accuracy:", accuracy_svm)


SVM Accuracy: 0.7893462469733656


In [29]:
from sklearn.metrics import confusion_matrix

# 혼동 행렬 계산
conf_matrix_svm = confusion_matrix(y_val, y_pred_svm)

# 혼동 행렬 출력
print("Confusion Matrix (SVM):")
print(conf_matrix_svm)

Confusion Matrix (SVM):
[[1956    0    0]
 [ 214    0    0]
 [ 308    0    0]]


In [27]:
from sklearn.metrics import confusion_matrix

# 혼동 행렬 계산
conf_matrix_svm = confusion_matrix(y_val, y_pred_svm)

# 혼동 행렬 출력
print("Confusion Matrix (SVM):")
print(conf_matrix_svm)

Confusion Matrix (SVM):
[[1956    0    0]
 [ 214    0    0]
 [ 308    0    0]]


In [30]:
from sklearn.metrics import confusion_matrix

# 혼동 행렬 계산
conf_matrix_logistic = confusion_matrix(y_val, y_pred_logistic)

# 혼동 행렬 출력
print("Confusion Matrix (Logistic Regression):")
print(conf_matrix_logistic)

Confusion Matrix (Logistic Regression):
[[1829    0  127]
 [ 177   13   24]
 [ 304    0    4]]


In [31]:
from sklearn.metrics import confusion_matrix

# 혼동 행렬 계산
conf_matrix_rf = confusion_matrix(y_val, y_pred_rf)

# 혼동 행렬 출력
print("Confusion Matrix (Random Forest):")
print(conf_matrix_rf)


Confusion Matrix (Random Forest):
[[ 473   15 1468]
 [   1  172   41]
 [ 234   29   45]]
